#!/bin/bash

#SBATCH --job-name=testingprepserial1             # Name shown for this job in the Slurm queue
#SBATCH --nodes=1                                 # Serial jobs usually run on one node/machine
#SBATCH --ntasks=1                                # Run one task/process
#SBATCH --cpus-per-task=1                         # Use one CPU core for the task

#SBATCH --output=%x-%j.out
#SBATCH --error=%x-%j.err






alces_prepare_job() {
  job_dir="$HOME/prepared/${SLURM_JOB_NAME}-${SLURM_JOB_ID}"

  mkdir -p "$job_dir"
  cd "$job_dir" || exit 1
}

alces_prepare_job


echo "Running serial job: testingprepserial1"     # Print which job is running

echo 'No command provided'                        # Run the user's command
